In [93]:
!pip install matplotlib
!pip install seaborn

Requirement already satisfied: matplotlib in c:\users\kumar\anaconda3\lib\site-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\kumar\anaconda3\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\kumar\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\kumar\anaconda3\lib\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\kumar\anaconda3\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\kumar\anaconda3\lib\site-packages (from matplotlib) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\kumar\anaconda3\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\kumar\anaconda3\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\kumar\anaconda3\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\kumar\anaconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\kumar\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in c:\users\kumar\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\kumar\anaconda3\lib\site-packages (from seaborn) (2.1.3)
Requirement already satisfied: pandas>=1.2 in c:\users\kumar\anaconda3\lib\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\kumar\anaconda3\lib\site-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\kumar\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\kumar\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\kumar\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\kumar\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\kumar\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\kumar\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\kumar\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\kumar\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kumar\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kumar\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\kumar\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [94]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [95]:
events=pd.read_csv("Raw_Data/events.csv")
customers=pd.read_csv("Raw_Data/customers.csv");
Order_items=pd.read_csv("Raw_Data/order_items.csv")
Orders=pd.read_csv("Raw_Data/orders.csv")
Products=pd.read_csv("Raw_Data/products.csv")
Reviews=pd.read_csv("Raw_Data/reviews.csv")
Sessions=pd.read_csv("Raw_Data/sessions.csv")

In [97]:
events.shape

(760958, 10)

In [98]:
events.head()

,event_id,session_id,timestamp,event_type,product_id,qty,cart_size,payment,discount_pct,amount_usd
0,1,1,2021-12-27T00:08:36,page_view,93.0,NaN,NaN,NaN,NaN,NaN
1,2,1,2021-12-27T00:16:36,page_view,1005.0,NaN,NaN,NaN,NaN,NaN
2,3,1,2021-12-27T00:18:01,add_to_cart,1005.0,1.0,NaN,NaN,NaN,NaN
3,4,1,2021-12-27T00:45:36,page_view,918.0,NaN,NaN,NaN,NaN,NaN
4,5,1,2021-12-27T01:03:36,page_view,946.0,NaN,NaN,NaN,NaN,NaN

In [99]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760958 entries, 0 to 760957
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   event_id      760958 non-null  int64
 1   session_id    760958 non-null  int64
 2   timestamp     760958 non-null  object
 3   event_type    760958 non-null  object
 4   product_id    682469 non-null  float64
 5   qty           143126 non-null  float64
 6   cart_size     44909 non-null   float64
 7   payment       33580 non-null   object
 8   discount_pct  33580 non-null   float64
 9   amount_usd    33580 non-null   float64
dtypes: float64(5), int64(2), object(3)
memory usage: 58.1+ MB

In [100]:
events.isnull().sum()

event_id             0
session_id           0
timestamp            0
event_type           0
product_id       78489
qty             617832
cart_size       716049
payment         727378
discount_pct    727378
amount_usd      727378
dtype: int64

In [101]:
events.duplicated().sum()

np.int64(0)

In [102]:
events["event_id"].duplicated().sum()

np.int64(0)

In [103]:
events["timestamp"]=pd.to_datetime(events["timestamp"])

In [104]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760958 entries, 0 to 760957
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   event_id      760958 non-null  int64
 1   session_id    760958 non-null  int64
 2   timestamp     760958 non-null  datetime64[ns]
 3   event_type    760958 non-null  object
 4   product_id    682469 non-null  float64
 5   qty           143126 non-null  float64
 6   cart_size     44909 non-null   float64
 7   payment       33580 non-null   object
 8   discount_pct  33580 non-null   float64
 9   amount_usd    33580 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(2), object(2)
memory usage: 58.1+ MB

In [105]:
events["event_type"].value_counts()

event_type
page_view      539343
add_to_cart    143126
checkout        44909
purchase        33580
Name: count, dtype: int64

In [106]:
events["session_id"].duplicated().sum()

np.int64(640958)

In [107]:
print(events.columns.tolist())

['event_id', 'session_id', 'timestamp', 'event_type', 'product_id', 'qty', 'cart_size', 'payment', 'discount_pct', 'amount_usd']

In [108]:
events["event_type"] = events["event_type"].astype(str)

In [109]:
events["payment"] = events["payment"].astype(str)

In [110]:
events["product_id"] = events["product_id"].astype("Int64")

In [111]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760958 entries, 0 to 760957
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   event_id      760958 non-null  int64
 1   session_id    760958 non-null  int64
 2   timestamp     760958 non-null  datetime64[ns]
 3   event_type    760958 non-null  object
 4   product_id    682469 non-null  Int64
 5   qty           143126 non-null  float64
 6   cart_size     44909 non-null   float64
 7   payment       760958 non-null  object
 8   discount_pct  33580 non-null   float64
 9   amount_usd    33580 non-null   float64
dtypes: Int64(1), datetime64[ns](1), float64(4), int64(2), object(2)
memory usage: 58.8+ MB

In [112]:
events[events["discount_pct"]>100]

Empty DataFrame
Columns: [event_id, session_id, timestamp, event_type, product_id, qty, cart_size, payment, discount_pct, amount_usd]
Index: []

In [113]:
events[events["discount_pct"]<0]

Empty DataFrame
Columns: [event_id, session_id, timestamp, event_type, product_id, qty, cart_size, payment, discount_pct, amount_usd]
Index: []

In [114]:
events.to_csv("Clean_Data/events.csv", index=False)

In [115]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       20000 non-null  int64
 1   name              20000 non-null  object
 2   email             20000 non-null  object
 3   country           20000 non-null  object
 4   age               20000 non-null  int64
 5   signup_date       20000 non-null  object
 6   marketing_opt_in  20000 non-null  bool
 7   variant           20000 non-null  object
dtypes: bool(1), int64(2), object(5)
memory usage: 1.1+ MB

In [116]:
customers["signup_date"]=pd.to_datetime(customers["signup_date"])

In [117]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       20000 non-null  int64
 1   name              20000 non-null  object
 2   email             20000 non-null  object
 3   country           20000 non-null  object
 4   age               20000 non-null  int64
 5   signup_date       20000 non-null  datetime64[ns]
 6   marketing_opt_in  20000 non-null  bool
 7   variant           20000 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(2), object(4)
memory usage: 1.1+ MB

In [118]:
customers["name"]=customers["name"].astype(str)
customers["email"]=customers["email"].astype(str)
customers["country"]=customers["country"].astype(str)

In [119]:
customers.isnull().sum()

customer_id         0
name                0
email               0
country             0
age                 0
signup_date         0
marketing_opt_in    0
variant             0
dtype: int64

In [120]:
customers.duplicated().sum()

np.int64(0)

In [121]:
customers["name"] = customers["name"].str.strip()
customers["email"] = customers["email"].str.strip().str.lower()
customers["country"] = customers["country"].str.strip().str.upper()

In [122]:
Orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33580 entries, 0 to 33579
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        33580 non-null  int64
 1   customer_id     33580 non-null  int64
 2   order_time      33580 non-null  object
 3   payment_method  33580 non-null  object
 4   discount_pct    33580 non-null  int64
 5   subtotal_usd    33580 non-null  float64
 6   total_usd       33580 non-null  float64
 7   country         33580 non-null  object
 8   device          33580 non-null  object
 9   source          33580 non-null  object
dtypes: float64(2), int64(3), object(5)
memory usage: 2.6+ MB

In [130]:
Orders.duplicated().sum()
Orders.isnull().sum()

order_id          0
customer_id       0
order_time        0
payment_method    0
discount_pct      0
subtotal_usd      0
total_usd         0
country           0
device            0
source            0
dtype: int64

In [123]:
Orders["order_time"]=pd.to_datetime(Orders["order_time"])

In [124]:
Orders[Orders["discount_pct"]>100]

Empty DataFrame
Columns: [order_id, customer_id, order_time, payment_method, discount_pct, subtotal_usd, total_usd, country, device, source]
Index: []

In [125]:
Orders[Orders["discount_pct"]<0]

Empty DataFrame
Columns: [order_id, customer_id, order_time, payment_method, discount_pct, subtotal_usd, total_usd, country, device, source]
Index: []

In [127]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       20000 non-null  int64
 1   name              20000 non-null  object
 2   email             20000 non-null  object
 3   country           20000 non-null  object
 4   age               20000 non-null  int64
 5   signup_date       20000 non-null  datetime64[ns]
 6   marketing_opt_in  20000 non-null  bool
 7   variant           20000 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(2), object(4)
memory usage: 1.1+ MB

In [131]:
Orders.head()

,order_id,customer_id,order_time,payment_method,discount_pct,subtotal_usd,total_usd,country,device,source
0,1,13917,2025-01-31 23:07:42,card,20,107.15,85.72,PL,desktop,organic
1,2,1022,2024-02-19 01:17:50,card,0,116.17,116.17,FR,tablet,organic
2,3,6145,2024-12-04 20:24:13,card,0,137.35,137.35,US,mobile,organic
3,4,3152,2024-07-17 08:50:47,card,15,32.18,27.35,BR,mobile,email
4,5,12378,2020-08-21 16:54:16,card,0,238.09,238.09,NL,desktop,paid

In [136]:
Orders[Orders["subtotal_usd"]<0]

Empty DataFrame
Columns: [order_id, customer_id, order_time, payment_method, discount_pct, subtotal_usd, total_usd, country, device, source]
Index: []

In [137]:
Order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59163 entries, 0 to 59162
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        59163 non-null  int64
 1   product_id      59163 non-null  int64
 2   unit_price_usd  59163 non-null  float64
 3   quantity        59163 non-null  int64
 4   line_total_usd  59163 non-null  float64
dtypes: float64(2), int64(3)
memory usage: 2.3 MB

In [138]:
Order_items.isnull().sum()

order_id          0
product_id        0
unit_price_usd    0
quantity          0
line_total_usd    0
dtype: int64

In [139]:
Order_items.duplicated().sum()

np.int64(73)

In [140]:
duplicates = Order_items[Order_items.duplicated()]
print(duplicates)

       order_id  product_id  unit_price_usd  quantity  line_total_usd
1134        629         528          173.62         1          173.62
1361        754          24           42.86         1           42.86
2412       1359        1148            6.96         1            6.96
3335       1895         866           25.45         1           25.45
4609       2626        1064           36.15         1           36.15
...         ...         ...             ...       ...             ...
52243     29630         476           29.44         1           29.44
52957     30032         374           66.86         1           66.86
53419     30285         444           26.35         1           26.35
55320     31418         377            5.50         1            5.50
58229     33065         387           31.86         1           31.86

[73 rows x 5 columns]

In [141]:
Order_items["order_id"].duplicated().sum()

np.int64(25583)

In [142]:
Order_items["order_id"].nunique()

33580

In [143]:
len(Order_items)

59163

In [144]:
Order_items.groupby("order_id").size().describe()

count    33580.000000
mean         1.761852
std          0.941490
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max          7.000000
dtype: float64

In [145]:
product_orders = (
    Order_items.groupby("product_id")["order_id"]
    .nunique()
    .sort_values(ascending=False)
)

product_orders.head(10)

product_id
496     139
442     123
404     122
861     114
392     113
504     111
358     111
769     111
366     111
1148    111
Name: order_id, dtype: int64

In [146]:
Products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  1197 non-null   int64
 1   category    1197 non-null   object
 2   name        1197 non-null   object
 3   price_usd   1197 non-null   float64
 4   cost_usd    1197 non-null   float64
 5   margin_usd  1197 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 56.2+ KB

In [147]:
Products.isnull().sum()

product_id    0
category      0
name          0
price_usd     0
cost_usd      0
margin_usd    0
dtype: int64

In [148]:
Products.duplicated().sum()

np.int64(0)

In [150]:
Products[Products["cost_usd"]<0]

Empty DataFrame
Columns: [product_id, category, name, price_usd, cost_usd, margin_usd]
Index: []

In [152]:
Products["category"] = Products["category"].str.strip()
Products["name"] = Products["name"].str.strip()

# Standardize category names
Products["category"] = Products["category"].str.title()

In [154]:
Products["product_id"] = Products["product_id"].astype(int)

Products["price_usd"] = pd.to_numeric(
    Products["price_usd"],
    errors="coerce"
)

Products["cost_usd"] = pd.to_numeric(
    Products["cost_usd"],
    errors="coerce"
)
Products["margin_usd"] = pd.to_numeric(
    Products["margin_usd"],
    errors="coerce"
)

In [156]:
Products["calculated_margin"] = (
    Products["price_usd"] -
    Products["cost_usd"]
)

margin_errors = Products[
    abs(
        Products["margin_usd"] -
        Products["calculated_margin"]
    ) > 0.01
]

print("Margin Errors:", len(margin_errors))

Margin Errors: 0

In [157]:
Reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10780 entries, 0 to 10779
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    10780 non-null  int64
 1   order_id     10780 non-null  int64
 2   product_id   10780 non-null  int64
 3   rating       10780 non-null  int64
 4   review_text  10780 non-null  object
 5   review_time  10780 non-null  object
dtypes: int64(4), object(2)
memory usage: 505.4+ KB

In [159]:
Reviews.isnull().sum()

review_id      0
order_id       0
product_id     0
rating         0
review_text    0
review_time    0
dtype: int64

In [160]:
Reviews.duplicated().sum()

np.int64(0)

In [161]:
Reviews.head()

,review_id,order_id,product_id,rating,review_text,review_time
0,1,4,1157,2,Not great quality.,2022-02-01T00:00:00
1,2,7,405,4,Good value for money!,2020-03-07T00:00:00
2,3,7,487,5,"Excellent product, highly recommend!",2024-12-26T00:00:00
3,4,7,442,5,"Excellent product, highly recommend!",2021-03-18T00:00:00
4,5,7,348,4,Good value for money!,2025-09-30T00:00:00

In [162]:
Reviews["review_time"]=pd.to_datetime(Reviews["review_time"])

In [163]:
Reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10780 entries, 0 to 10779
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    10780 non-null  int64
 1   order_id     10780 non-null  int64
 2   product_id   10780 non-null  int64
 3   rating       10780 non-null  int64
 4   review_text  10780 non-null  object
 5   review_time  10780 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 505.4+ KB

In [167]:
Reviews["rating"] = pd.to_numeric(
     Reviews["rating"],
    errors="coerce"
)

# Keep valid ratings only
Reviews = Reviews[
    Reviews["rating"].between(1, 5)
]

In [169]:
Reviews.groupby("order_id").size().sort_values(
    ascending=False
).head()

order_id
6939     7
33305    6
1371     6
23808    6
10629    6
dtype: int64

In [170]:
Reviews[
    Reviews.duplicated(
        subset=["order_id", "product_id"],
        keep=False
    )
]

,review_id,order_id,product_id,rating,review_text,review_time
194,195,629,528,5,"Excellent product, highly recommend!",2025-04-29
195,196,629,528,4,Good value for money!,2022-06-19
1156,1157,3486,903,3,Okay overall.,2025-06-18
1157,1158,3486,903,5,"Excellent product, highly recommend!",2024-06-13
1453,1454,4445,959,5,"Excellent product, highly recommend!",2023-11-30
1454,1455,4445,959,3,Okay overall.,2021-04-18
3845,3846,11894,504,5,"Excellent product, highly recommend!",2024-12-17
3847,3848,11894,504,5,"Excellent product, highly recommend!",2025-04-12
4858,4859,15255,751,5,"Excellent product, highly recommend!",2024-12-10
4859,4860,15255,751,1,"Very disappointed, would not buy again.",2020-02-29
6801,6802,21582,1032,4,Good value for money!,2025-08-13
6802,6803,21582,1032,4,Good value for money!,2023-05-07
6827,6828,21665,344,5,"Excellent product, highly recommend!",2023-09-11
6828,6829,21665,344,3,Okay overall.,2022-04-22
7061,7062,22338,57,4,Good value for money!,2023-09-03
7062,7063,22338,57,5,"Excellent product, highly recommend!",2021-06-11
7816,7817,24654,239,3,Okay overall.,2021-10-10
7817,7818,24654,239,5,"Excellent product, highly recommend!",2022-08-18
8065,8066,25405,94,4,Good value for money!,2023-01-13
8066,8067,25405,94,4,Good value for money!,2024-11-30
8334,8335,26196,336,5,"Excellent product, highly recommend!",2020-05-05
8336,8337,26196,336,4,Good value for money!,2020-04-23
8510,8511,26662,1039,5,"Excellent product, highly recommend!",2021-10-24
8511,8512,26662,1039,1,"Very disappointed, would not buy again.",2025-06-19
8651,8652,27087,1174,5,"Excellent product, highly recommend!",2024-05-31
8652,8653,27087,1174,3,Okay overall.,2023-03-31
9286,9287,28953,889,4,Good value for money!,2024-08-21
9288,9289,28953,889,5,"Excellent product, highly recommend!",2022-03-13
10567,10568,33065,387,5,"Excellent product, highly recommend!",2024-09-09
10568,10569,33065,387,5,"Excellent product, highly recommend!",2023-11-14

In [171]:
Sessions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   session_id   120000 non-null  int64
 1   customer_id  120000 non-null  int64
 2   start_time   120000 non-null  object
 3   device       120000 non-null  object
 4   source       120000 non-null  object
 5   country      120000 non-null  object
dtypes: int64(2), object(4)
memory usage: 5.5+ MB

In [172]:
Sessions["start_time"]=pd.to_datetime(Sessions["start_time"])

In [173]:
Sessions.isnull().sum()

session_id     0
customer_id    0
start_time     0
device         0
source         0
country        0
dtype: int64

In [174]:
Sessions.duplicated().sum()

np.int64(0)

In [175]:
Reviews["review_id"] = pd.to_numeric(
    Reviews["review_id"],
    errors="coerce"
)

Reviews["order_id"] = pd.to_numeric(
    Reviews["order_id"],
    errors="coerce"
)

Reviews["product_id"] = pd.to_numeric(
    Reviews["product_id"],
    errors="coerce"
)

Reviews["rating"] = pd.to_numeric(
    Reviews["rating"],
    errors="coerce"
)

Reviews["review_time"] = pd.to_datetime(
    Reviews["review_time"],
    errors="coerce"
)

In [176]:
Sessions["device"] = (
    Sessions["device"]
    .astype(str)
    .str.strip()
    .str.lower()
)

Sessions["source"] = (
    Sessions["source"]
    .astype(str)
    .str.strip()
    .str.lower()
)

Sessions["country"] = (
    Sessions["country"]
    .astype(str)
    .str.strip()
    .str.upper()
)

In [177]:
Sessions["source"].value_counts()

source
organic     40776
direct      29861
paid        14465
social      14389
email       10949
referral     9560
Name: count, dtype: int64

In [178]:
Sessions["device"].value_counts()

device
mobile     65942
desktop    45547
tablet      8511
Name: count, dtype: int64

In [180]:
customers.to_csv("Clean_Data/customers.csv",index=False)

In [181]:
Sessions.to_csv("Clean_Data/Sessions.csv",index=False)

In [183]:
Orders.to_csv("Clean_Data/Orders.csv",index=False)

In [185]:
Order_items.to_csv("Clean_Data/Order_items.csv",index=False)

In [ ]:
Orders.to_csv("Clean_Data/Orders.csv",index=False)